spring:
  application:
    name: user-service-server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://nonabili-mariadb.ctoqgyyqkbir.ap-northeast-2.rds.amazonaws.com/nona
    username: admin
    password: nonabili1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:nonabili1234@localhost:8761/eureka